# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
 - stage: Build
   jobs:
   - job: FirstJob
     steps:
     - bash: echo Hello, world!
     - bash: echo Build number is $(Build.BuildNumber)
     - bash: echo Source branch is $(Build.SourceBranchName)
     - bash: echo Source Diretory is $(Build.SourcesDirectory)
     - bash: echo Default working directory is $(System.DefaultWorkingDirectory)
     - bash: echo Staging Directory is $(Build.ArtifactStagingDirectory)
   - job: SecondJob
     steps:
       - bash: echo Second Job
       - bash: ls -R $(Build.ArtifactStagingDirectory)
       - task: CopyFiles@2
         inputs:
          SourceFolder: '$(Build.SourcesDirectory)'
          Contents: |
             **/*.yaml
             **/*.tf
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
       - bash: ls -R $(Build.ArtifactStagingDirectory)


